build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"c3VwcG9ydGVyaW5vOlVYcE0kckphJCZYcjJ2N1ZAS0hoIW9YS1VhM3JGQA==\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "supporterino/dice:${CI_COMMIT_SHORT_SHA}"
